### PR TITLE
Cmake add version + Update .travis & appveyor from Petri

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by rgleason** [comment]
Tom-r
I don't know why I see those "Merge Pull Request #1 #2 & #5 from TDan"  
are in there!

If this is this a problem?  If so, I will correct it and make a new PR.

**Comment by rgleason** [comment]
Now I recall that you reverted these while on the water, so your version does not have them. 
I am a bit confused about this however. 

1. I have pulled from your repository recently to get current. Shouldn't that have overriden these TDan Changes?

2. If I "revert" these now, what happens, since I would assume the diff between our two repositories  would show no difference?

3. If you were to accept this PR (not suggesting it), what would happen?  Would those git commits added to your repository in the exact same location as before, and then your "revert" would also remain in place, and nothing would change in how your repository is now?

**Comment by rgleason** [comment]
I guess I will squash these TDan commits and make a new PR.  Now Closing.

**Comment by rgleason** [comment]
After more study, it looks like Thomas pulled from TDan repository, so my pull of TDan changes is different, thus they show up in this PR to go to Tom-r repository.  
I do need to drop them with squash I believe, in both my master and this branch.

**Comment by rgleason** [comment]
When I try to git rebas -i ...   squash my "Merge Pull Requests from,..."  Tdan, tom-r etc. those commits do not show up!   So I cannot "squash" them.

So does this mean it is OK for Tom_r to merge and only the 
- ov50 appveyor.yml
- Update .travis.yml
- cmake-version-add-os
- fix-text
Will be added to his repository?

I am going to rebase and squash the above anyway. Then see.

**Comment by BernardMayer** [comment]
Hello all

Apologize my poor English.Tactics-pi has it tryed on Raspbian (Stretch édition) OS ?

Thanks by advance
Bernard Mayer

    Le lundi 29 juillet 2019 à 16:35:29 UTC+2, Rick Gleason <notifications@github.com> a écrit :  
 
 
When I try to git rebas -i ... squash my "Merge Pull Requests from,..." Tdan, tom-r etc. those commits do not show up! So I cannot "squash" them.

So does this mean it is OK for Tom_r to merge and only the
   
   - ov50 appveyor.yml
   - Update .travis.yml
   - cmake-version-add-os
   - fix-text   
Will be added to his repository?

I am going to rebase and squash the above anyway. Then see.

**Comment by rgleason** [comment]
Rebase and squash was not the best way to do this. I created a new branch and git reset --hard upstream/master   (tom_r repos) and then made my changes and pushed to my fork.  Then going to make PR after it builds and I can try it.

**Pull request closed without merging**
